namespace Household_book
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.button_rep = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_ab = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_tech = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_anim = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_hoz = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.button_pl = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(1049, 0);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(102, 24);
            this.bunifuFormControlBox1.TabIndex = 21;
            this.bunifuFormControlBox1.HelpClicked += new System.EventHandler(this.bunifuFormControlBox1_HelpClicked);
            // 
            // menuStrip1
            // 
            this.menuStrip1.BackColor = System.Drawing.Color.PapayaWhip;
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1151, 24);
            this.menuStrip1.TabIndex = 20;
            this.menuStrip1.Text = "menuStrip1";
            this.menuStrip1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseDown);
            this.menuStrip1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseMove);
            this.menuStrip1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseUp);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.PapayaWhip;
            this.panel1.Controls.Add(this.button_rep);
            this.panel1.Controls.Add(this.button_ab);
            this.panel1.Controls.Add(this.button_exit);
            this.panel1.Controls.Add(this.button_tech);
            this.panel1.Controls.Add(this.button_anim);
            this.panel1.Controls.Add(this.button_hoz);
            this.panel1.Controls.Add(this.pictureBox3);
            this.panel1.Controls.Add(this.button_pl);
            this.panel1.Location = new System.Drawing.Point(0, 23);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(218, 699);
            this.panel1.TabIndex = 23;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuLabel1.Location = new System.Drawing.Point(40, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(394, 16);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Хозяйственная книга Администрации Березовского сельсовета\r\n";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox4
            // 
            this.pictureBox4.BackColor = System.Drawing.Color.PapayaWhip;
            this.pictureBox4.Image = global::Household_book.Properties.Resources.logo;
            this.pictureBox4.Location = new System.Drawing.Point(5, 2);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(33, 20);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox4.TabIndex = 22;
            this.pictureBox4.TabStop = false;
            // 
            // button_rep
            // 
            this.button_rep.AllowAnimations = true;
            this.button_rep.AllowMouseEffects = true;
            this.button_rep.AllowToggling = false;
            this.button_rep.AnimationSpeed = 200;
            this.button_rep.AutoGenerateColors = false;
            this.button_rep.AutoRoundBorders = false;
            this.button_rep.AutoSizeLeftIcon = true;
            this.button_rep.AutoSizeRightIcon = true;
            this.button_rep.BackColor = System.Drawing.Color.Transparent;
            this.button_rep.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_rep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_rep.BackgroundImage")));
            this.button_rep.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.ButtonText = "Отчеты";
            this.button_rep.ButtonTextMarginLeft = 0;
            this.button_rep.ColorContrastOnClick = 45;
            this.button_rep.ColorContrastOnHover = 45;
            this.button_rep.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.button_rep.CustomizableEdges = borderEdges8;
            this.button_rep.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_rep.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_rep.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_rep.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_rep.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_rep.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_rep.ForeColor = System.Drawing.Color.White;
            this.button_rep.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_rep.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_rep.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_rep.IconMarginLeft = 11;
            this.button_rep.IconPadding = 10;
            this.button_rep.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_rep.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_rep.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_rep.IconSize = 25;
            this.button_rep.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.IdleBorderRadius = 30;
            this.button_rep.IdleBorderThickness = 1;
            this.button_rep.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.IdleIconLeftImage = global::Household_book.Properties.Resources.report;
            this.button_rep.IdleIconRightImage = null;
            this.button_rep.IndicateFocus = false;
            this.button_rep.Location = new System.Drawing.Point(5, 512);
            this.button_rep.Name = "button_rep";
            this.button_rep.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_rep.OnDisabledState.BorderRadius = 30;
            this.button_rep.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnDisabledState.BorderThickness = 1;
            this.button_rep.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_rep.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_rep.OnDisabledState.IconLeftImage = null;
            this.button_rep.OnDisabledState.IconRightImage = null;
            this.button_rep.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_rep.onHoverState.BorderRadius = 30;
            this.button_rep.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.onHoverState.BorderThickness = 1;
            this.button_rep.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_rep.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_rep.onHoverState.IconLeftImage = null;
            this.button_rep.onHoverState.IconRightImage = null;
            this.button_rep.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnIdleState.BorderRadius = 30;
            this.button_rep.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnIdleState.BorderThickness = 1;
            this.button_rep.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_rep.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.report;
            this.button_rep.OnIdleState.IconRightImage = null;
            this.button_rep.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnPressedState.BorderRadius = 30;
            this.button_rep.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnPressedState.BorderThickness = 1;
            this.button_rep.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_rep.OnPressedState.IconLeftImage = null;
            this.button_rep.OnPressedState.IconRightImage = null;
            this.button_rep.Size = new System.Drawing.Size(207, 51);
            this.button_rep.TabIndex = 30;
            this.button_rep.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_rep.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_rep.TextMarginLeft = 0;
            this.button_rep.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_rep.UseDefaultRadiusAndThickness = true;
            // 
            // button_ab
            // 
            this.button_ab.AllowAnimations = true;
            this.button_ab.AllowMouseEffects = true;
            this.button_ab.AllowToggling = false;
            this.button_ab.AnimationSpeed = 200;
            this.button_ab.AutoGenerateColors = false;
            this.button_ab.AutoRoundBorders = false;
            this.button_ab.AutoSizeLeftIcon = true;
            this.button_ab.AutoSizeRightIcon = true;
            this.button_ab.BackColor = System.Drawing.Color.Transparent;
            this.button_ab.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_ab.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_ab.BackgroundImage")));
            this.button_ab.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.ButtonText = "Справка";
            this.button_ab.ButtonTextMarginLeft = 0;
            this.button_ab.ColorContrastOnClick = 45;
            this.button_ab.ColorContrastOnHover = 45;
            this.button_ab.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.button_ab.CustomizableEdges = borderEdges9;
            this.button_ab.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_ab.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_ab.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_ab.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_ab.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_ab.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_ab.ForeColor = System.Drawing.Color.White;
            this.button_ab.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_ab.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_ab.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_ab.IconMarginLeft = 11;
            this.button_ab.IconPadding = 10;
            this.button_ab.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_ab.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_ab.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_ab.IconSize = 25;
            this.button_ab.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.IdleBorderRadius = 30;
            this.button_ab.IdleBorderThickness = 1;
            this.button_ab.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.IdleIconLeftImage = global::Household_book.Properties.Resources.about;
            this.button_ab.IdleIconRightImage = null;
            this.button_ab.IndicateFocus = false;
            this.button_ab.Location = new System.Drawing.Point(5, 569);
            this.button_ab.Name = "button_ab";
            this.button_ab.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_ab.OnDisabledState.BorderRadius = 30;
            this.button_ab.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnDisabledState.BorderThickness = 1;
            this.button_ab.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_ab.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_ab.OnDisabledState.IconLeftImage = null;
            this.button_ab.OnDisabledState.IconRightImage = null;
            this.button_ab.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_ab.onHoverState.BorderRadius = 30;
            this.button_ab.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.onHoverState.BorderThickness = 1;
            this.button_ab.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_ab.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_ab.onHoverState.IconLeftImage = null;
            this.button_ab.onHoverState.IconRightImage = null;
            this.button_ab.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnIdleState.BorderRadius = 30;
            this.button_ab.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnIdleState.BorderThickness = 1;
            this.button_ab.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_ab.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.about;
            this.button_ab.OnIdleState.IconRightImage = null;
            this.button_ab.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnPressedState.BorderRadius = 30;
            this.button_ab.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnPressedState.BorderThickness = 1;
            this.button_ab.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_ab.OnPressedState.IconLeftImage = null;
            this.button_ab.OnPressedState.IconRightImage = null;
            this.button_ab.Size = new System.Drawing.Size(207, 51);
            this.button_ab.TabIndex = 29;
            this.button_ab.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_ab.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_ab.TextMarginLeft = 0;
            this.button_ab.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_ab.UseDefaultRadiusAndThickness = true;
            // 
            // button_exit
            // 
            this.button_exit.AllowAnimations = true;
            this.button_exit.AllowMouseEffects = true;
            this.button_exit.AllowToggling = false;
            this.button_exit.AnimationSpeed = 200;
            this.button_exit.AutoGenerateColors = false;
            this.button_exit.AutoRoundBorders = false;
            this.button_exit.AutoSizeLeftIcon = true;
            this.button_exit.AutoSizeRightIcon = true;
            this.button_exit.BackColor = System.Drawing.Color.Transparent;
            this.button_exit.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_exit.BackgroundImage")));
            this.button_exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.ButtonText = "Выйти";
            this.button_exit.ButtonTextMarginLeft = 0;
            this.button_exit.ColorContrastOnClick = 45;
            this.button_exit.ColorContrastOnHover = 45;
            this.button_exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.button_exit.CustomizableEdges = borderEdges10;
            this.button_exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_exit.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_exit.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_exit.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_exit.ForeColor = System.Drawing.Color.White;
            this.button_exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_exit.IconMarginLeft = 11;
            this.button_exit.IconPadding = 10;
            this.button_exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_exit.IconSize = 25;
            this.button_exit.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.IdleBorderRadius = 30;
            this.button_exit.IdleBorderThickness = 1;
            this.button_exit.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.IdleIconLeftImage = global::Household_book.Properties.Resources.exit;
            this.button_exit.IdleIconRightImage = null;
            this.button_exit.IndicateFocus = false;
            this.button_exit.Location = new System.Drawing.Point(5, 626);
            this.button_exit.Name = "button_exit";
            this.button_exit.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_exit.OnDisabledState.BorderRadius = 30;
            this.button_exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnDisabledState.BorderThickness = 1;
            this.button_exit.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_exit.OnDisabledState.IconLeftImage = null;
            this.button_exit.OnDisabledState.IconRightImage = null;
            this.button_exit.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_exit.onHoverState.BorderRadius = 30;
            this.button_exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.onHoverState.BorderThickness = 1;
            this.button_exit.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_exit.onHoverState.IconLeftImage = null;
            this.button_exit.onHoverState.IconRightImage = null;
            this.button_exit.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnIdleState.BorderRadius = 30;
            this.button_exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnIdleState.BorderThickness = 1;
            this.button_exit.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_exit.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.exit;
            this.button_exit.OnIdleState.IconRightImage = null;
            this.button_exit.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnPressedState.BorderRadius = 30;
            this.button_exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnPressedState.BorderThickness = 1;
            this.button_exit.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_exit.OnPressedState.IconLeftImage = null;
            this.button_exit.OnPressedState.IconRightImage = null;
            this.button_exit.Size = new System.Drawing.Size(207, 51);
            this.button_exit.TabIndex = 28;
            this.button_exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_exit.TextMarginLeft = 0;
            this.button_exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_exit.UseDefaultRadiusAndThickness = true;
            // 
            // button_tech
            // 
            this.button_tech.AllowAnimations = true;
            this.button_tech.AllowMouseEffects = true;
            this.button_tech.AllowToggling = false;
            this.button_tech.AnimationSpeed = 200;
            this.button_tech.AutoGenerateColors = false;
            this.button_tech.AutoRoundBorders = false;
            this.button_tech.AutoSizeLeftIcon = true;
            this.button_tech.AutoSizeRightIcon = true;
            this.button_tech.BackColor = System.Drawing.Color.Transparent;
            this.button_tech.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_tech.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_tech.BackgroundImage")));
            this.button_tech.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.ButtonText = "Техника";
            this.button_tech.ButtonTextMarginLeft = 0;
            this.button_tech.ColorContrastOnClick = 45;
            this.button_tech.ColorContrastOnHover = 45;
            this.button_tech.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.button_tech.CustomizableEdges = borderEdges11;
            this.button_tech.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_tech.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_tech.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_tech.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_tech.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_tech.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_tech.ForeColor = System.Drawing.Color.White;
            this.button_tech.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_tech.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_tech.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_tech.IconMarginLeft = 11;
            this.button_tech.IconPadding = 10;
            this.button_tech.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_tech.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_tech.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_tech.IconSize = 25;
            this.button_tech.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.IdleBorderRadius = 30;
            this.button_tech.IdleBorderThickness = 1;
            this.button_tech.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.IdleIconLeftImage = global::Household_book.Properties.Resources.technic;
            this.button_tech.IdleIconRightImage = null;
            this.button_tech.IndicateFocus = false;
            this.button_tech.Location = new System.Drawing.Point(5, 306);
            this.button_tech.Name = "button_tech";
            this.button_tech.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_tech.OnDisabledState.BorderRadius = 30;
            this.button_tech.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnDisabledState.BorderThickness = 1;
            this.button_tech.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_tech.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_tech.OnDisabledState.IconLeftImage = null;
            this.button_tech.OnDisabledState.IconRightImage = null;
            this.button_tech.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_tech.onHoverState.BorderRadius = 30;
            this.button_tech.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.onHoverState.BorderThickness = 1;
            this.button_tech.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_tech.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_tech.onHoverState.IconLeftImage = null;
            this.button_tech.onHoverState.IconRightImage = null;
            this.button_tech.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnIdleState.BorderRadius = 30;
            this.button_tech.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnIdleState.BorderThickness = 1;
            this.button_tech.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_tech.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.technic;
            this.button_tech.OnIdleState.IconRightImage = null;
            this.button_tech.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnPressedState.BorderRadius = 30;
            this.button_tech.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnPressedState.BorderThickness = 1;
            this.button_tech.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_tech.OnPressedState.IconLeftImage = null;
            this.button_tech.OnPressedState.IconRightImage = null;
            this.button_tech.Size = new System.Drawing.Size(207, 51);
            this.button_tech.TabIndex = 27;
            this.button_tech.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_tech.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_tech.TextMarginLeft = 0;
            this.button_tech.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_tech.UseDefaultRadiusAndThickness = true;
            // 
            // button_anim
            // 
            this.button_anim.AllowAnimations = true;
            this.button_anim.AllowMouseEffects = true;
            this.button_anim.AllowToggling = false;
            this.button_anim.AnimationSpeed = 200;
            this.button_anim.AutoGenerateColors = false;
            this.button_anim.AutoRoundBorders = false;
            this.button_anim.AutoSizeLeftIcon = true;
            this.button_anim.AutoSizeRightIcon = true;
            this.button_anim.BackColor = System.Drawing.Color.Transparent;
            this.button_anim.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_anim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_anim.BackgroundImage")));
            this.button_anim.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.ButtonText = "Животные";
            this.button_anim.ButtonTextMarginLeft = 0;
            this.button_anim.ColorContrastOnClick = 45;
            this.button_anim.ColorContrastOnHover = 45;
            this.button_anim.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.button_anim.CustomizableEdges = borderEdges12;
            this.button_anim.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_anim.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_anim.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_anim.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_anim.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_anim.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_anim.ForeColor = System.Drawing.Color.White;
            this.button_anim.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_anim.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_anim.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_anim.IconMarginLeft = 11;
            this.button_anim.IconPadding = 10;
            this.button_anim.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_anim.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_anim.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_anim.IconSize = 25;
            this.button_anim.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.IdleBorderRadius = 30;
            this.button_anim.IdleBorderThickness = 1;
            this.button_anim.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.IdleIconLeftImage = global::Household_book.Properties.Resources.animals;
            this.button_anim.IdleIconRightImage = null;
            this.button_anim.IndicateFocus = false;
            this.button_anim.Location = new System.Drawing.Point(5, 249);
            this.button_anim.Name = "button_anim";
            this.button_anim.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_anim.OnDisabledState.BorderRadius = 30;
            this.button_anim.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnDisabledState.BorderThickness = 1;
            this.button_anim.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_anim.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_anim.OnDisabledState.IconLeftImage = null;
            this.button_anim.OnDisabledState.IconRightImage = null;
            this.button_anim.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_anim.onHoverState.BorderRadius = 30;
            this.button_anim.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.onHoverState.BorderThickness = 1;
            this.button_anim.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_anim.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_anim.onHoverState.IconLeftImage = null;
            this.button_anim.onHoverState.IconRightImage = null;
            this.button_anim.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnIdleState.BorderRadius = 30;
            this.button_anim.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnIdleState.BorderThickness = 1;
            this.button_anim.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_anim.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.animals;
            this.button_anim.OnIdleState.IconRightImage = null;
            this.button_anim.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnPressedState.BorderRadius = 30;
            this.button_anim.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnPressedState.BorderThickness = 1;
            this.button_anim.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_anim.OnPressedState.IconLeftImage = null;
            this.button_anim.OnPressedState.IconRightImage = null;
            this.button_anim.Size = new System.Drawing.Size(207, 51);
            this.button_anim.TabIndex = 26;
            this.button_anim.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_anim.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_anim.TextMarginLeft = 0;
            this.button_anim.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_anim.UseDefaultRadiusAndThickness = true;
            // 
            // button_hoz
            // 
            this.button_hoz.AllowAnimations = true;
            this.button_hoz.AllowMouseEffects = true;
            this.button_hoz.AllowToggling = false;
            this.button_hoz.AnimationSpeed = 200;
            this.button_hoz.AutoGenerateColors = false;
            this.button_hoz.AutoRoundBorders = false;
            this.button_hoz.AutoSizeLeftIcon = true;
            this.button_hoz.AutoSizeRightIcon = true;
            this.button_hoz.BackColor = System.Drawing.Color.Transparent;
            this.button_hoz.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_hoz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_hoz.BackgroundImage")));
            this.button_hoz.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.ButtonText = "Подсобное \r\nхозяйства";
            this.button_hoz.ButtonTextMarginLeft = 0;
            this.button_hoz.ColorContrastOnClick = 45;
            this.button_hoz.ColorContrastOnHover = 45;
            this.button_hoz.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.button_hoz.CustomizableEdges = borderEdges13;
            this.button_hoz.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_hoz.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_hoz.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_hoz.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_hoz.ForeColor = System.Drawing.Color.White;
            this.button_hoz.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_hoz.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_hoz.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_hoz.IconMarginLeft = 11;
            this.button_hoz.IconPadding = 10;
            this.button_hoz.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_hoz.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_hoz.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_hoz.IconSize = 25;
            this.button_hoz.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.IdleBorderRadius = 30;
            this.button_hoz.IdleBorderThickness = 1;
            this.button_hoz.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.IdleIconLeftImage = global::Household_book.Properties.Resources.hoz;
            this.button_hoz.IdleIconRightImage = null;
            this.button_hoz.IndicateFocus = false;
            this.button_hoz.Location = new System.Drawing.Point(5, 192);
            this.button_hoz.Name = "button_hoz";
            this.button_hoz.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.OnDisabledState.BorderRadius = 30;
            this.button_hoz.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnDisabledState.BorderThickness = 1;
            this.button_hoz.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_hoz.OnDisabledState.IconLeftImage = null;
            this.button_hoz.OnDisabledState.IconRightImage = null;
            this.button_hoz.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_hoz.onHoverState.BorderRadius = 30;
            this.button_hoz.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.onHoverState.BorderThickness = 1;
            this.button_hoz.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_hoz.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.onHoverState.IconLeftImage = null;
            this.button_hoz.onHoverState.IconRightImage = null;
            this.button_hoz.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnIdleState.BorderRadius = 30;
            this.button_hoz.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnIdleState.BorderThickness = 1;
            this.button_hoz.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.hoz;
            this.button_hoz.OnIdleState.IconRightImage = null;
            this.button_hoz.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnPressedState.BorderRadius = 30;
            this.button_hoz.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnPressedState.BorderThickness = 1;
            this.button_hoz.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.OnPressedState.IconLeftImage = null;
            this.button_hoz.OnPressedState.IconRightImage = null;
            this.button_hoz.Size = new System.Drawing.Size(207, 51);
            this.button_hoz.TabIndex = 25;
            this.button_hoz.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_hoz.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_hoz.TextMarginLeft = 0;
            this.button_hoz.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_hoz.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Image = global::Household_book.Properties.Resources.logo;
            this.pictureBox3.Location = new System.Drawing.Point(12, 5);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(184, 115);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 24;
            this.pictureBox3.TabStop = false;
            // 
            // button_pl
            // 
            this.button_pl.AllowAnimations = true;
            this.button_pl.AllowMouseEffects = true;
            this.button_pl.AllowToggling = false;
            this.button_pl.AnimationSpeed = 200;
            this.button_pl.AutoGenerateColors = false;
            this.button_pl.AutoRoundBorders = false;
            this.button_pl.AutoSizeLeftIcon = true;
            this.button_pl.AutoSizeRightIcon = true;
            this.button_pl.BackColor = System.Drawing.Color.Transparent;
            this.button_pl.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_pl.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_pl.BackgroundImage")));
            this.button_pl.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.ButtonText = "Жители";
            this.button_pl.ButtonTextMarginLeft = 0;
            this.button_pl.ColorContrastOnClick = 45;
            this.button_pl.ColorContrastOnHover = 45;
            this.button_pl.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.button_pl.CustomizableEdges = borderEdges14;
            this.button_pl.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_pl.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_pl.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_pl.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_pl.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_pl.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_pl.ForeColor = System.Drawing.Color.White;
            this.button_pl.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_pl.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_pl.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_pl.IconMarginLeft = 11;
            this.button_pl.IconPadding = 10;
            this.button_pl.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_pl.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_pl.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_pl.IconSize = 25;
            this.button_pl.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.IdleBorderRadius = 30;
            this.button_pl.IdleBorderThickness = 1;
            this.button_pl.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.IdleIconLeftImage = global::Household_book.Properties.Resources.people;
            this.button_pl.IdleIconRightImage = null;
            this.button_pl.IndicateFocus = false;
            this.button_pl.Location = new System.Drawing.Point(5, 135);
            this.button_pl.Name = "button_pl";
            this.button_pl.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_pl.OnDisabledState.BorderRadius = 30;
            this.button_pl.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnDisabledState.BorderThickness = 1;
            this.button_pl.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_pl.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_pl.OnDisabledState.IconLeftImage = null;
            this.button_pl.OnDisabledState.IconRightImage = null;
            this.button_pl.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_pl.onHoverState.BorderRadius = 30;
            this.button_pl.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.onHoverState.BorderThickness = 1;
            this.button_pl.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_pl.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_pl.onHoverState.IconLeftImage = null;
            this.button_pl.onHoverState.IconRightImage = null;
            this.button_pl.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnIdleState.BorderRadius = 30;
            this.button_pl.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnIdleState.BorderThickness = 1;
            this.button_pl.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_pl.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.people;
            this.button_pl.OnIdleState.IconRightImage = null;
            this.button_pl.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnPressedState.BorderRadius = 30;
            this.button_pl.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnPressedState.BorderThickness = 1;
            this.button_pl.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_pl.OnPressedState.IconLeftImage = null;
            this.button_pl.OnPressedState.IconRightImage = null;
            this.button_pl.Size = new System.Drawing.Size(207, 51);
            this.button_pl.TabIndex = 6;
            this.button_pl.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_pl.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_pl.TextMarginLeft = 0;
            this.button_pl.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_pl.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(236, 164);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(903, 530);
            this.bunifuDataGridView1.TabIndex = 24;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.bunifuLabel2);
            this.panel2.Location = new System.Drawing.Point(236, 28);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(903, 130);
            this.panel2.TabIndex = 25;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(3, 3);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(128, 39);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "Жители";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Moccasin;
            this.ClientSize = new System.Drawing.Size(1151, 712);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.menuStrip1);
            this.Controls.Add(this.panel1);
            this.Name = "Main";
            this.Text = "Main";
            this.Load += new System.EventHandler(this.Main_Load);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox4;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.BindingSource bindingSource1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_pl;
        private System.Windows.Forms.PictureBox pictureBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_rep;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_ab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_exit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_tech;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_anim;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_hoz;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
    }
}