namespace Household_book
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.bindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.text_adress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.date = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.text_login = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.button_anim = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_hoz = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_pl = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_tech = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_ab = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.button_rep = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(944, 0);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(102, 24);
            this.bunifuFormControlBox1.TabIndex = 21;
            this.bunifuFormControlBox1.HelpClicked += new System.EventHandler(this.bunifuFormControlBox1_HelpClicked);
            // 
            // menuStrip1
            // 
            this.menuStrip1.BackColor = System.Drawing.Color.PapayaWhip;
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1046, 24);
            this.menuStrip1.TabIndex = 20;
            this.menuStrip1.Text = "menuStrip1";
            this.menuStrip1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseDown);
            this.menuStrip1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseMove);
            this.menuStrip1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.menuStrip1_MouseUp);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuLabel1.Location = new System.Drawing.Point(40, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(394, 16);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Хозяйственная книга Администрации Березовского сельсовета\r\n";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox4
            // 
            this.pictureBox4.BackColor = System.Drawing.Color.PapayaWhip;
            this.pictureBox4.Image = global::Household_book.Properties.Resources.logo;
            this.pictureBox4.Location = new System.Drawing.Point(5, 2);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(33, 20);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox4.TabIndex = 22;
            this.pictureBox4.TabStop = false;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BackgroundColor = System.Drawing.Color.Moccasin;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.PapayaWhip;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Century Gothic", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.PapayaWhip;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.Transparent;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Moccasin;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.Moccasin;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Century Gothic", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.Transparent;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.Moccasin;
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.PapayaWhip;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(236, 178);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(798, 516);
            this.bunifuDataGridView1.TabIndex = 24;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellContentClick);
            // 
            // text_adress
            // 
            this.text_adress.AcceptsReturn = false;
            this.text_adress.AcceptsTab = false;
            this.text_adress.AnimationSpeed = 200;
            this.text_adress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.text_adress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.text_adress.AutoSizeHeight = true;
            this.text_adress.BackColor = System.Drawing.Color.Transparent;
            this.text_adress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("text_adress.BackgroundImage")));
            this.text_adress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.text_adress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.text_adress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.text_adress.BorderColorIdle = System.Drawing.Color.Silver;
            this.text_adress.BorderRadius = 30;
            this.text_adress.BorderThickness = 1;
            this.text_adress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.text_adress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.text_adress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.text_adress.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.text_adress.DefaultText = "";
            this.text_adress.FillColor = System.Drawing.Color.White;
            this.text_adress.HideSelection = true;
            this.text_adress.IconLeft = null;
            this.text_adress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.text_adress.IconPadding = 10;
            this.text_adress.IconRight = null;
            this.text_adress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.text_adress.Lines = new string[0];
            this.text_adress.Location = new System.Drawing.Point(158, 99);
            this.text_adress.MaxLength = 32767;
            this.text_adress.MinimumSize = new System.Drawing.Size(1, 1);
            this.text_adress.Modified = false;
            this.text_adress.Multiline = false;
            this.text_adress.Name = "text_adress";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_adress.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.text_adress.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_adress.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_adress.OnIdleState = stateProperties4;
            this.text_adress.Padding = new System.Windows.Forms.Padding(3);
            this.text_adress.PasswordChar = '\0';
            this.text_adress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.text_adress.PlaceholderText = "Введите адрес прописки";
            this.text_adress.ReadOnly = false;
            this.text_adress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.text_adress.SelectedText = "";
            this.text_adress.SelectionLength = 0;
            this.text_adress.SelectionStart = 0;
            this.text_adress.ShortcutsEnabled = true;
            this.text_adress.Size = new System.Drawing.Size(634, 32);
            this.text_adress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.text_adress.TabIndex = 32;
            this.text_adress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.text_adress.TextMarginBottom = 0;
            this.text_adress.TextMarginLeft = 3;
            this.text_adress.TextMarginTop = 1;
            this.text_adress.TextPlaceholder = "Введите адрес прописки";
            this.text_adress.UseSystemPasswordChar = false;
            this.text_adress.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(14, 105);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(137, 19);
            this.bunifuLabel5.TabIndex = 31;
            this.bunifuLabel5.Text = "Адрес прописки";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(460, 65);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(127, 19);
            this.bunifuLabel4.TabIndex = 30;
            this.bunifuLabel4.Text = "Дата рождения";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(14, 65);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(36, 19);
            this.bunifuLabel3.TabIndex = 29;
            this.bunifuLabel3.Text = "ФИО";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // date
            // 
            this.date.BackColor = System.Drawing.Color.Transparent;
            this.date.BorderColor = System.Drawing.Color.White;
            this.date.BorderRadius = 17;
            this.date.Color = System.Drawing.Color.White;
            this.date.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.date.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.date.DisabledColor = System.Drawing.Color.Gray;
            this.date.DisplayWeekNumbers = false;
            this.date.DPHeight = 0;
            this.date.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.date.FillDatePicker = false;
            this.date.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.date.ForeColor = System.Drawing.Color.Black;
            this.date.Icon = ((System.Drawing.Image)(resources.GetObject("date.Icon")));
            this.date.IconColor = System.Drawing.Color.DarkGray;
            this.date.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.date.LeftTextMargin = 5;
            this.date.Location = new System.Drawing.Point(593, 58);
            this.date.MinimumSize = new System.Drawing.Size(4, 32);
            this.date.Name = "date";
            this.date.Size = new System.Drawing.Size(199, 32);
            this.date.TabIndex = 28;
            this.date.Value = new System.DateTime(2025, 4, 20, 20, 27, 0, 0);
            // 
            // text_login
            // 
            this.text_login.AcceptsReturn = false;
            this.text_login.AcceptsTab = false;
            this.text_login.AnimationSpeed = 200;
            this.text_login.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.text_login.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.text_login.AutoSizeHeight = true;
            this.text_login.BackColor = System.Drawing.Color.Transparent;
            this.text_login.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("text_login.BackgroundImage")));
            this.text_login.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.text_login.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.text_login.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.text_login.BorderColorIdle = System.Drawing.Color.Silver;
            this.text_login.BorderRadius = 30;
            this.text_login.BorderThickness = 1;
            this.text_login.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.text_login.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.text_login.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.text_login.DefaultFont = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.text_login.DefaultText = "";
            this.text_login.FillColor = System.Drawing.Color.White;
            this.text_login.HideSelection = true;
            this.text_login.IconLeft = null;
            this.text_login.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.text_login.IconPadding = 10;
            this.text_login.IconRight = null;
            this.text_login.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.text_login.Lines = new string[0];
            this.text_login.Location = new System.Drawing.Point(56, 58);
            this.text_login.MaxLength = 32767;
            this.text_login.MinimumSize = new System.Drawing.Size(1, 1);
            this.text_login.Modified = false;
            this.text_login.Multiline = false;
            this.text_login.Name = "text_login";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_login.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.text_login.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_login.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.text_login.OnIdleState = stateProperties8;
            this.text_login.Padding = new System.Windows.Forms.Padding(3);
            this.text_login.PasswordChar = '\0';
            this.text_login.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.text_login.PlaceholderText = "Введите ФИО";
            this.text_login.ReadOnly = false;
            this.text_login.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.text_login.SelectedText = "";
            this.text_login.SelectionLength = 0;
            this.text_login.SelectionStart = 0;
            this.text_login.ShortcutsEnabled = true;
            this.text_login.Size = new System.Drawing.Size(373, 32);
            this.text_login.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.text_login.TabIndex = 26;
            this.text_login.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.text_login.TextMarginBottom = 0;
            this.text_login.TextMarginLeft = 3;
            this.text_login.TextMarginTop = 1;
            this.text_login.TextPlaceholder = "Введите ФИО";
            this.text_login.UseSystemPasswordChar = false;
            this.text_login.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(14, 12);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(128, 39);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "Жители";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.PapayaWhip;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 30;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Controls.Add(this.button_rep);
            this.bunifuPanel1.Controls.Add(this.button_ab);
            this.bunifuPanel1.Controls.Add(this.button_exit);
            this.bunifuPanel1.Controls.Add(this.button_tech);
            this.bunifuPanel1.Controls.Add(this.button_pl);
            this.bunifuPanel1.Controls.Add(this.button_hoz);
            this.bunifuPanel1.Controls.Add(this.button_anim);
            this.bunifuPanel1.Location = new System.Drawing.Point(5, 26);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(225, 678);
            this.bunifuPanel1.TabIndex = 26;
            // 
            // button_anim
            // 
            this.button_anim.AllowAnimations = true;
            this.button_anim.AllowMouseEffects = true;
            this.button_anim.AllowToggling = false;
            this.button_anim.AnimationSpeed = 200;
            this.button_anim.AutoGenerateColors = false;
            this.button_anim.AutoRoundBorders = false;
            this.button_anim.AutoSizeLeftIcon = true;
            this.button_anim.AutoSizeRightIcon = true;
            this.button_anim.BackColor = System.Drawing.Color.Transparent;
            this.button_anim.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_anim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_anim.BackgroundImage")));
            this.button_anim.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.ButtonText = "Животные";
            this.button_anim.ButtonTextMarginLeft = 0;
            this.button_anim.ColorContrastOnClick = 45;
            this.button_anim.ColorContrastOnHover = 45;
            this.button_anim.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.button_anim.CustomizableEdges = borderEdges7;
            this.button_anim.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_anim.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_anim.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_anim.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_anim.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_anim.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_anim.ForeColor = System.Drawing.Color.White;
            this.button_anim.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_anim.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_anim.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_anim.IconMarginLeft = 11;
            this.button_anim.IconPadding = 10;
            this.button_anim.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_anim.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_anim.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_anim.IconSize = 25;
            this.button_anim.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.IdleBorderRadius = 30;
            this.button_anim.IdleBorderThickness = 1;
            this.button_anim.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.IdleIconLeftImage = global::Household_book.Properties.Resources.animals;
            this.button_anim.IdleIconRightImage = null;
            this.button_anim.IndicateFocus = false;
            this.button_anim.Location = new System.Drawing.Point(8, 273);
            this.button_anim.Name = "button_anim";
            this.button_anim.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_anim.OnDisabledState.BorderRadius = 30;
            this.button_anim.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnDisabledState.BorderThickness = 1;
            this.button_anim.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_anim.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_anim.OnDisabledState.IconLeftImage = null;
            this.button_anim.OnDisabledState.IconRightImage = null;
            this.button_anim.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_anim.onHoverState.BorderRadius = 30;
            this.button_anim.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.onHoverState.BorderThickness = 1;
            this.button_anim.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_anim.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_anim.onHoverState.IconLeftImage = null;
            this.button_anim.onHoverState.IconRightImage = null;
            this.button_anim.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnIdleState.BorderRadius = 30;
            this.button_anim.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnIdleState.BorderThickness = 1;
            this.button_anim.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_anim.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.animals;
            this.button_anim.OnIdleState.IconRightImage = null;
            this.button_anim.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnPressedState.BorderRadius = 30;
            this.button_anim.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_anim.OnPressedState.BorderThickness = 1;
            this.button_anim.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_anim.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_anim.OnPressedState.IconLeftImage = null;
            this.button_anim.OnPressedState.IconRightImage = null;
            this.button_anim.Size = new System.Drawing.Size(207, 51);
            this.button_anim.TabIndex = 26;
            this.button_anim.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_anim.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_anim.TextMarginLeft = 0;
            this.button_anim.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_anim.UseDefaultRadiusAndThickness = true;
            // 
            // button_hoz
            // 
            this.button_hoz.AllowAnimations = true;
            this.button_hoz.AllowMouseEffects = true;
            this.button_hoz.AllowToggling = false;
            this.button_hoz.AnimationSpeed = 200;
            this.button_hoz.AutoGenerateColors = false;
            this.button_hoz.AutoRoundBorders = false;
            this.button_hoz.AutoSizeLeftIcon = true;
            this.button_hoz.AutoSizeRightIcon = true;
            this.button_hoz.BackColor = System.Drawing.Color.Transparent;
            this.button_hoz.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_hoz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_hoz.BackgroundImage")));
            this.button_hoz.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.ButtonText = "Подсобное \r\nхозяйства";
            this.button_hoz.ButtonTextMarginLeft = 0;
            this.button_hoz.ColorContrastOnClick = 45;
            this.button_hoz.ColorContrastOnHover = 45;
            this.button_hoz.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.button_hoz.CustomizableEdges = borderEdges6;
            this.button_hoz.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_hoz.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_hoz.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_hoz.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_hoz.ForeColor = System.Drawing.Color.White;
            this.button_hoz.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_hoz.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_hoz.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_hoz.IconMarginLeft = 11;
            this.button_hoz.IconPadding = 10;
            this.button_hoz.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_hoz.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_hoz.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_hoz.IconSize = 25;
            this.button_hoz.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.IdleBorderRadius = 30;
            this.button_hoz.IdleBorderThickness = 1;
            this.button_hoz.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.IdleIconLeftImage = global::Household_book.Properties.Resources.hoz;
            this.button_hoz.IdleIconRightImage = null;
            this.button_hoz.IndicateFocus = false;
            this.button_hoz.Location = new System.Drawing.Point(8, 216);
            this.button_hoz.Name = "button_hoz";
            this.button_hoz.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.OnDisabledState.BorderRadius = 30;
            this.button_hoz.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnDisabledState.BorderThickness = 1;
            this.button_hoz.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_hoz.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_hoz.OnDisabledState.IconLeftImage = null;
            this.button_hoz.OnDisabledState.IconRightImage = null;
            this.button_hoz.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_hoz.onHoverState.BorderRadius = 30;
            this.button_hoz.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.onHoverState.BorderThickness = 1;
            this.button_hoz.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_hoz.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.onHoverState.IconLeftImage = null;
            this.button_hoz.onHoverState.IconRightImage = null;
            this.button_hoz.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnIdleState.BorderRadius = 30;
            this.button_hoz.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnIdleState.BorderThickness = 1;
            this.button_hoz.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.hoz;
            this.button_hoz.OnIdleState.IconRightImage = null;
            this.button_hoz.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnPressedState.BorderRadius = 30;
            this.button_hoz.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_hoz.OnPressedState.BorderThickness = 1;
            this.button_hoz.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_hoz.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_hoz.OnPressedState.IconLeftImage = null;
            this.button_hoz.OnPressedState.IconRightImage = null;
            this.button_hoz.Size = new System.Drawing.Size(207, 51);
            this.button_hoz.TabIndex = 25;
            this.button_hoz.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_hoz.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_hoz.TextMarginLeft = 0;
            this.button_hoz.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_hoz.UseDefaultRadiusAndThickness = true;
            // 
            // button_pl
            // 
            this.button_pl.AllowAnimations = true;
            this.button_pl.AllowMouseEffects = true;
            this.button_pl.AllowToggling = false;
            this.button_pl.AnimationSpeed = 200;
            this.button_pl.AutoGenerateColors = false;
            this.button_pl.AutoRoundBorders = false;
            this.button_pl.AutoSizeLeftIcon = true;
            this.button_pl.AutoSizeRightIcon = true;
            this.button_pl.BackColor = System.Drawing.Color.Transparent;
            this.button_pl.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_pl.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_pl.BackgroundImage")));
            this.button_pl.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.ButtonText = "Жители";
            this.button_pl.ButtonTextMarginLeft = 0;
            this.button_pl.ColorContrastOnClick = 45;
            this.button_pl.ColorContrastOnHover = 45;
            this.button_pl.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.button_pl.CustomizableEdges = borderEdges5;
            this.button_pl.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_pl.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_pl.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_pl.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_pl.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_pl.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_pl.ForeColor = System.Drawing.Color.White;
            this.button_pl.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_pl.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_pl.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_pl.IconMarginLeft = 11;
            this.button_pl.IconPadding = 10;
            this.button_pl.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_pl.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_pl.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_pl.IconSize = 25;
            this.button_pl.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.IdleBorderRadius = 30;
            this.button_pl.IdleBorderThickness = 1;
            this.button_pl.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.IdleIconLeftImage = global::Household_book.Properties.Resources.people;
            this.button_pl.IdleIconRightImage = null;
            this.button_pl.IndicateFocus = false;
            this.button_pl.Location = new System.Drawing.Point(8, 159);
            this.button_pl.Name = "button_pl";
            this.button_pl.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_pl.OnDisabledState.BorderRadius = 30;
            this.button_pl.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnDisabledState.BorderThickness = 1;
            this.button_pl.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_pl.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_pl.OnDisabledState.IconLeftImage = null;
            this.button_pl.OnDisabledState.IconRightImage = null;
            this.button_pl.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_pl.onHoverState.BorderRadius = 30;
            this.button_pl.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.onHoverState.BorderThickness = 1;
            this.button_pl.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_pl.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_pl.onHoverState.IconLeftImage = null;
            this.button_pl.onHoverState.IconRightImage = null;
            this.button_pl.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnIdleState.BorderRadius = 30;
            this.button_pl.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnIdleState.BorderThickness = 1;
            this.button_pl.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_pl.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.people;
            this.button_pl.OnIdleState.IconRightImage = null;
            this.button_pl.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnPressedState.BorderRadius = 30;
            this.button_pl.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_pl.OnPressedState.BorderThickness = 1;
            this.button_pl.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_pl.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_pl.OnPressedState.IconLeftImage = null;
            this.button_pl.OnPressedState.IconRightImage = null;
            this.button_pl.Size = new System.Drawing.Size(207, 51);
            this.button_pl.TabIndex = 6;
            this.button_pl.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_pl.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_pl.TextMarginLeft = 0;
            this.button_pl.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_pl.UseDefaultRadiusAndThickness = true;
            this.button_pl.Click += new System.EventHandler(this.button_pl_Click);
            // 
            // button_tech
            // 
            this.button_tech.AllowAnimations = true;
            this.button_tech.AllowMouseEffects = true;
            this.button_tech.AllowToggling = false;
            this.button_tech.AnimationSpeed = 200;
            this.button_tech.AutoGenerateColors = false;
            this.button_tech.AutoRoundBorders = false;
            this.button_tech.AutoSizeLeftIcon = true;
            this.button_tech.AutoSizeRightIcon = true;
            this.button_tech.BackColor = System.Drawing.Color.Transparent;
            this.button_tech.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_tech.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_tech.BackgroundImage")));
            this.button_tech.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.ButtonText = "Техника";
            this.button_tech.ButtonTextMarginLeft = 0;
            this.button_tech.ColorContrastOnClick = 45;
            this.button_tech.ColorContrastOnHover = 45;
            this.button_tech.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.button_tech.CustomizableEdges = borderEdges4;
            this.button_tech.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_tech.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_tech.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_tech.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_tech.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_tech.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_tech.ForeColor = System.Drawing.Color.White;
            this.button_tech.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_tech.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_tech.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_tech.IconMarginLeft = 11;
            this.button_tech.IconPadding = 10;
            this.button_tech.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_tech.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_tech.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_tech.IconSize = 25;
            this.button_tech.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.IdleBorderRadius = 30;
            this.button_tech.IdleBorderThickness = 1;
            this.button_tech.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.IdleIconLeftImage = global::Household_book.Properties.Resources.technic;
            this.button_tech.IdleIconRightImage = null;
            this.button_tech.IndicateFocus = false;
            this.button_tech.Location = new System.Drawing.Point(8, 330);
            this.button_tech.Name = "button_tech";
            this.button_tech.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_tech.OnDisabledState.BorderRadius = 30;
            this.button_tech.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnDisabledState.BorderThickness = 1;
            this.button_tech.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_tech.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_tech.OnDisabledState.IconLeftImage = null;
            this.button_tech.OnDisabledState.IconRightImage = null;
            this.button_tech.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_tech.onHoverState.BorderRadius = 30;
            this.button_tech.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.onHoverState.BorderThickness = 1;
            this.button_tech.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_tech.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_tech.onHoverState.IconLeftImage = null;
            this.button_tech.onHoverState.IconRightImage = null;
            this.button_tech.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnIdleState.BorderRadius = 30;
            this.button_tech.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnIdleState.BorderThickness = 1;
            this.button_tech.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_tech.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.technic;
            this.button_tech.OnIdleState.IconRightImage = null;
            this.button_tech.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnPressedState.BorderRadius = 30;
            this.button_tech.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_tech.OnPressedState.BorderThickness = 1;
            this.button_tech.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_tech.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_tech.OnPressedState.IconLeftImage = null;
            this.button_tech.OnPressedState.IconRightImage = null;
            this.button_tech.Size = new System.Drawing.Size(207, 51);
            this.button_tech.TabIndex = 27;
            this.button_tech.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_tech.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_tech.TextMarginLeft = 0;
            this.button_tech.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_tech.UseDefaultRadiusAndThickness = true;
            // 
            // button_exit
            // 
            this.button_exit.AllowAnimations = true;
            this.button_exit.AllowMouseEffects = true;
            this.button_exit.AllowToggling = false;
            this.button_exit.AnimationSpeed = 200;
            this.button_exit.AutoGenerateColors = false;
            this.button_exit.AutoRoundBorders = false;
            this.button_exit.AutoSizeLeftIcon = true;
            this.button_exit.AutoSizeRightIcon = true;
            this.button_exit.BackColor = System.Drawing.Color.Transparent;
            this.button_exit.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_exit.BackgroundImage")));
            this.button_exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.ButtonText = "Выйти";
            this.button_exit.ButtonTextMarginLeft = 0;
            this.button_exit.ColorContrastOnClick = 45;
            this.button_exit.ColorContrastOnHover = 45;
            this.button_exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.button_exit.CustomizableEdges = borderEdges3;
            this.button_exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_exit.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_exit.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_exit.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_exit.ForeColor = System.Drawing.Color.White;
            this.button_exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_exit.IconMarginLeft = 11;
            this.button_exit.IconPadding = 10;
            this.button_exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_exit.IconSize = 25;
            this.button_exit.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.IdleBorderRadius = 30;
            this.button_exit.IdleBorderThickness = 1;
            this.button_exit.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.IdleIconLeftImage = global::Household_book.Properties.Resources.exit;
            this.button_exit.IdleIconRightImage = null;
            this.button_exit.IndicateFocus = false;
            this.button_exit.Location = new System.Drawing.Point(8, 616);
            this.button_exit.Name = "button_exit";
            this.button_exit.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_exit.OnDisabledState.BorderRadius = 30;
            this.button_exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnDisabledState.BorderThickness = 1;
            this.button_exit.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_exit.OnDisabledState.IconLeftImage = null;
            this.button_exit.OnDisabledState.IconRightImage = null;
            this.button_exit.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_exit.onHoverState.BorderRadius = 30;
            this.button_exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.onHoverState.BorderThickness = 1;
            this.button_exit.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_exit.onHoverState.IconLeftImage = null;
            this.button_exit.onHoverState.IconRightImage = null;
            this.button_exit.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnIdleState.BorderRadius = 30;
            this.button_exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnIdleState.BorderThickness = 1;
            this.button_exit.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_exit.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.exit;
            this.button_exit.OnIdleState.IconRightImage = null;
            this.button_exit.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnPressedState.BorderRadius = 30;
            this.button_exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_exit.OnPressedState.BorderThickness = 1;
            this.button_exit.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_exit.OnPressedState.IconLeftImage = null;
            this.button_exit.OnPressedState.IconRightImage = null;
            this.button_exit.Size = new System.Drawing.Size(207, 51);
            this.button_exit.TabIndex = 28;
            this.button_exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_exit.TextMarginLeft = 0;
            this.button_exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_exit.UseDefaultRadiusAndThickness = true;
            // 
            // button_ab
            // 
            this.button_ab.AllowAnimations = true;
            this.button_ab.AllowMouseEffects = true;
            this.button_ab.AllowToggling = false;
            this.button_ab.AnimationSpeed = 200;
            this.button_ab.AutoGenerateColors = false;
            this.button_ab.AutoRoundBorders = false;
            this.button_ab.AutoSizeLeftIcon = true;
            this.button_ab.AutoSizeRightIcon = true;
            this.button_ab.BackColor = System.Drawing.Color.Transparent;
            this.button_ab.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_ab.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_ab.BackgroundImage")));
            this.button_ab.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.ButtonText = "Справка";
            this.button_ab.ButtonTextMarginLeft = 0;
            this.button_ab.ColorContrastOnClick = 45;
            this.button_ab.ColorContrastOnHover = 45;
            this.button_ab.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.button_ab.CustomizableEdges = borderEdges2;
            this.button_ab.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_ab.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_ab.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_ab.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_ab.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_ab.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_ab.ForeColor = System.Drawing.Color.White;
            this.button_ab.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_ab.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_ab.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_ab.IconMarginLeft = 11;
            this.button_ab.IconPadding = 10;
            this.button_ab.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_ab.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_ab.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_ab.IconSize = 25;
            this.button_ab.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.IdleBorderRadius = 30;
            this.button_ab.IdleBorderThickness = 1;
            this.button_ab.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.IdleIconLeftImage = global::Household_book.Properties.Resources.about;
            this.button_ab.IdleIconRightImage = null;
            this.button_ab.IndicateFocus = false;
            this.button_ab.Location = new System.Drawing.Point(8, 559);
            this.button_ab.Name = "button_ab";
            this.button_ab.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_ab.OnDisabledState.BorderRadius = 30;
            this.button_ab.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnDisabledState.BorderThickness = 1;
            this.button_ab.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_ab.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_ab.OnDisabledState.IconLeftImage = null;
            this.button_ab.OnDisabledState.IconRightImage = null;
            this.button_ab.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_ab.onHoverState.BorderRadius = 30;
            this.button_ab.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.onHoverState.BorderThickness = 1;
            this.button_ab.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_ab.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_ab.onHoverState.IconLeftImage = null;
            this.button_ab.onHoverState.IconRightImage = null;
            this.button_ab.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnIdleState.BorderRadius = 30;
            this.button_ab.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnIdleState.BorderThickness = 1;
            this.button_ab.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_ab.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.about;
            this.button_ab.OnIdleState.IconRightImage = null;
            this.button_ab.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnPressedState.BorderRadius = 30;
            this.button_ab.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_ab.OnPressedState.BorderThickness = 1;
            this.button_ab.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_ab.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_ab.OnPressedState.IconLeftImage = null;
            this.button_ab.OnPressedState.IconRightImage = null;
            this.button_ab.Size = new System.Drawing.Size(207, 51);
            this.button_ab.TabIndex = 29;
            this.button_ab.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_ab.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_ab.TextMarginLeft = 0;
            this.button_ab.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_ab.UseDefaultRadiusAndThickness = true;
            // 
            // button_rep
            // 
            this.button_rep.AllowAnimations = true;
            this.button_rep.AllowMouseEffects = true;
            this.button_rep.AllowToggling = false;
            this.button_rep.AnimationSpeed = 200;
            this.button_rep.AutoGenerateColors = false;
            this.button_rep.AutoRoundBorders = false;
            this.button_rep.AutoSizeLeftIcon = true;
            this.button_rep.AutoSizeRightIcon = true;
            this.button_rep.BackColor = System.Drawing.Color.Transparent;
            this.button_rep.BackColor1 = System.Drawing.Color.Goldenrod;
            this.button_rep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_rep.BackgroundImage")));
            this.button_rep.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.ButtonText = "Отчеты";
            this.button_rep.ButtonTextMarginLeft = 0;
            this.button_rep.ColorContrastOnClick = 45;
            this.button_rep.ColorContrastOnHover = 45;
            this.button_rep.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.button_rep.CustomizableEdges = borderEdges1;
            this.button_rep.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_rep.DisabledBorderColor = System.Drawing.Color.Gainsboro;
            this.button_rep.DisabledFillColor = System.Drawing.Color.Gainsboro;
            this.button_rep.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_rep.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.button_rep.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.button_rep.ForeColor = System.Drawing.Color.White;
            this.button_rep.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_rep.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_rep.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_rep.IconMarginLeft = 11;
            this.button_rep.IconPadding = 10;
            this.button_rep.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_rep.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_rep.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_rep.IconSize = 25;
            this.button_rep.IdleBorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.IdleBorderRadius = 30;
            this.button_rep.IdleBorderThickness = 1;
            this.button_rep.IdleFillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.IdleIconLeftImage = global::Household_book.Properties.Resources.report;
            this.button_rep.IdleIconRightImage = null;
            this.button_rep.IndicateFocus = false;
            this.button_rep.Location = new System.Drawing.Point(8, 502);
            this.button_rep.Name = "button_rep";
            this.button_rep.OnDisabledState.BorderColor = System.Drawing.Color.Gainsboro;
            this.button_rep.OnDisabledState.BorderRadius = 30;
            this.button_rep.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnDisabledState.BorderThickness = 1;
            this.button_rep.OnDisabledState.FillColor = System.Drawing.Color.Gainsboro;
            this.button_rep.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_rep.OnDisabledState.IconLeftImage = null;
            this.button_rep.OnDisabledState.IconRightImage = null;
            this.button_rep.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.button_rep.onHoverState.BorderRadius = 30;
            this.button_rep.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.onHoverState.BorderThickness = 1;
            this.button_rep.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.button_rep.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_rep.onHoverState.IconLeftImage = null;
            this.button_rep.onHoverState.IconRightImage = null;
            this.button_rep.OnIdleState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnIdleState.BorderRadius = 30;
            this.button_rep.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnIdleState.BorderThickness = 1;
            this.button_rep.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_rep.OnIdleState.IconLeftImage = global::Household_book.Properties.Resources.report;
            this.button_rep.OnIdleState.IconRightImage = null;
            this.button_rep.OnPressedState.BorderColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnPressedState.BorderRadius = 30;
            this.button_rep.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button_rep.OnPressedState.BorderThickness = 1;
            this.button_rep.OnPressedState.FillColor = System.Drawing.Color.Goldenrod;
            this.button_rep.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_rep.OnPressedState.IconLeftImage = null;
            this.button_rep.OnPressedState.IconRightImage = null;
            this.button_rep.Size = new System.Drawing.Size(207, 51);
            this.button_rep.TabIndex = 30;
            this.button_rep.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_rep.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_rep.TextMarginLeft = 0;
            this.button_rep.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_rep.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Black;
            this.bunifuPanel2.BorderRadius = 30;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.text_adress);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel2.Controls.Add(this.text_login);
            this.bunifuPanel2.Controls.Add(this.date);
            this.bunifuPanel2.Location = new System.Drawing.Point(236, 27);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(798, 145);
            this.bunifuPanel2.TabIndex = 33;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 30;
            this.bunifuPictureBox1.Image = global::Household_book.Properties.Resources.logo;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(14, 12);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(197, 128);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 31;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Moccasin;
            this.ClientSize = new System.Drawing.Size(1046, 708);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.menuStrip1);
            this.Name = "Main";
            this.Text = "Main";
            this.Load += new System.EventHandler(this.Main_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox4;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.BindingSource bindingSource1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox text_login;
        private Bunifu.UI.WinForms.BunifuDatePicker date;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox text_adress;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_rep;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_ab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_exit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_tech;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_pl;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_hoz;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button_anim;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
    }
}